export type ControlType =
    | 'checkbox-list'
    | 'autocompletes'
    | 'autocomplete'
    | 'email-input'
    | 'childArray'
    | 'date-input'
    | 'file-input'
    | 'url-input'
    | 'checkbox'
    | 'textarea'
    | 'divider'
    | 'select'
    | 'child'
    | 'input';
